#!/bin/zsh
# autor: edineifedel
# Recebe uma lista de projetos e atualiza as dependências snapshot (maven) entre os projetos

if [ $# -eq 0 ]; then
    echo "Usage: $(basename $0) [project1] [project2] [project3]"
    echo "Dica: A ordem da lista deve ser dos projetos folhas para os projetos raízes"
    exit 1
fi

WORKSPACE=/opt/workspace

cd $WORKSPACE

projects=($@)

for i in $projects; do
    cd $i
    # explain sed regex
    # ^.* descarta tudo que vem antes de <version>
    # .*$ descarta tudo que vem depois de <version>
    snapshotVersion=$(sed -n "s/^.*<version>\(.*-SNAPSHOT\)<\/version>.*$/\1/p" pom.xml)
    # itera sobre os projetos e troca para versão snapshot
    for j in $projects; do
        cd ..
        cd $j
        echo "Try change $i-$snapshotVersion in $j"
        # explain sed regex
        # 0,/(<.*$i.*>)(.+)(<\/.*$i.*>)/ -> para mudar a primeira ocorrência do pattern
        # (<.*$i.*>)(.+)(<\/.*$i.*>) -> pattern de <projeto>XX.YY.ZZ</projeto>
        # \1$snapshotVersion\3/ -> pattern de substituição <projeto>XX.YY-SNAPSHOT</projeto>
        sed -i -r "0,/(<.*$i.*>)(.+)(<\/.*$i.*>)/ s/(<.*$i.*>)(.+)(<\/.*$i.*>)/\1$snapshotVersion\3/g" pom.xml
    done;
    cd ..
done;
